export const THEME = {
  colors: {
    primary: "#f9f506",
    primaryOrange: "#FF6B42",
    primaryLight: "#FF8A65",
    secondaryBlue: "#EBF2FF",
    secondaryBlueDark: "#1E3A8A",
    kpiYellow: "#FFE082",
    backgroundLight: "#F2F2F2",
    backgroundDark: "var(--bg-surface)",
    surfaceLight: "var(--bg-void)",
    surfaceDark: "var(--bg-card)",
    overlayLight: "rgba(var(--bg-void-rgb), 0.5)",
    overlayDark: "rgba(var(--bg-void-rgb), 0.7)",
    blueCta: "#5B80FF",
    textPrimaryLight: "var(--border-color)333",
    textPrimaryDark: "#EEEEEE",
    textSecondaryLight: "var(--text-secondary)666",
    textSecondaryDark: "#AAAAAA",
    cardLight: "var(--bg-void)",
    cardDark: "var(--bg-card)",
    navInactive: "#9E9E9E",
    borderLight: "var(--border-color)",
    borderDark: "var(--border-color)333",
  },
};
